spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081/
          Predicates:
            - Path=/account-service/**
        - id: customer-service
          uri: http://localhost:8082/
          Predicates:
            - Path=/customer-service/**