spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: customer-service
          uri:  lb://customer-service
          predicates:
            - Path=/customer/**
