spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/account/**
        - id: customer-service
          uri:  http://localhost:8080
          predicates:
            - Path=/customer/**
          filters:
            - PrefixPath=/api
